CREATE TABLE ADRES(
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     panstwo VARCHAR(40) NOT NULL,
     miasto VARCHAR(40) NOT NULL,
     kodpoczt VARCHAR(6) NOT NULL,
     ulica VARCHAR(40) NOT NULL,
     nrbudynku INTEGER NOT NULL,
     nrlokalu INTEGER NOT NULL
);

CREATE TABLE OSOBA(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(400) NOT NULL,
surname VARCHAR(400) NOT NULL,
adres_id BIGINT NOT NULL,
email VARCHAR(400) NULL,
birthdate DATE NOT NULL,
phonenr VARCHAR(20) NULL
);


CREATE TABLE PRACOWNIK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    osoba_id BIGINT NOT NULL,
    pension DOUBLE NOT NULL
);

CREATE TABLE KLIENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    osoba_id BIGINT NOT NULL,
    points INTEGER NOT NULL,
    notrealized INTEGER NOT NULL
);


CREATE TABLE REZERWACJE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    klient_id BIGINT NOT NULL,
    trasa_id BIGINT NOT NULL,
    reservationnr INTEGER NOT NULL
);

CREATE TABLE TRASA(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    fee FLOAT(10) NOT NULL
);

CREATE TABLE TRASA_PRZYSTANEK(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trasa_id BIGINT NOT NULL,
    przystanek_id BIGINT NOT NULL
);

CREATE TABLE PRZYSTANEK(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stopname VARCHAR(40) NOT NULL,
    nextstop BIGINT NULL,
    prevstop BIGINT NULL
);

CREATE TABLE ROZKLAD(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trasa_id BIGINT NOT NULL,
    bus_id BIGINT NOT NULL,
    arrive TIME NOT NULL,
    depart TIME NOT NULL
);

CREATE TABLE BUS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stpar_id BIGINT NOT NULL,
    busmodel VARCHAR(40) NOT NULL,
    marka VARCHAR(40) NOT NULL,
    rokprod DATE NOT NULL,
    srspalanie VARCHAR(40) NULL,
    przebieg INTEGER NOT NULL,
    dostepnosc ENUM('NIE','TAK') NOT NULL,
    pojemnosc INTEGER NOT NULL
);

CREATE TABLE KIEROWCA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    osoba_id BIGINT NOT NULL,
    bus_id BIGINT NULL,
    pension DOUBLE NOT NULL
);


CREATE TABLE STALY_PARKING(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    adres_id BIGINT NOT NULL,
    maxiloscmiejsc INTEGER NOT NULL,
    czywolnemiejsce ENUM('NIE','TAK') NOT NULL
);

